# Generated by Django 3.1 on 2020-11-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='ans',
            field=models.TextField(default=''),
        ),
    ]
