# Generated by Django 3.2 on 2021-04-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_q'),
    ]

    operations = [
        migrations.DeleteModel(
            name='q',
        ),
    ]
